[project]
name = "Ai-Cognitive-Nexus-Mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.0.0",
    "fastmcp>=2.11.3",
    "agno>=1.7.11",
    "filelock>=3.19.1",
]
